### ISSUE TITLE
Add "Create your own subcollection" feature

### ISSUE THREAD

**Issue by JanelleJenstad** [UVicHCMC/BBTI#9]
The old site apparently had a feature whereby the user could compare two records records. We know this because MoEML had a link with this URL: `http://bbti.bodleian.ox.ac.uk/compare/?traderid=98995&amp;traderid=78894`
 
It is possible to reproduce that, but not immediately.

**Comment by martindholmes** [comment]
I think we can do better than that. We can adapt the system we created for DVPP, whereby you can create an anthology for yourself using just the ids of specific poems, which are consolidated into a single URL. The anthology page on the site then parses that URL, retrieves the individual records, and builds a table of links:

https://dvpp.uvic.ca/createAnthology.html

In BBTI, instead of a page of links, we could actually retrieve all the pages for those records, extract the record component, and build them into a single page.

So this would be a two-stage thing: 

1. Make the record's numeric id visible in the record itself, so people can easily find it (at the moment, you can see it in the URL, but not in the record itself).
2. Create the anthology construction page (where you enter the list of ids and a title for the anthology) and the anthology rendering page (which the resulting URL points to, and which does the job of building the anthology for you).

This would enable researchers to share small collections of records and examine them easily alongside each other, just through URLs.

**Comment by martindholmes** [comment]
I think this is now basically working; following testing we can integrate instructions and links for the feature. Go to create_collection.html in the dev build to see and test.

**Comment by martindholmes** [comment]
Now in latest release.
